- link:
    ~/.vim:                  editors/vim
    ~/.vimrc:                editors/vim/vimrc
    ~/.config/nvim:          editors/vim
    ~/.config/nvim/init.vim: editors/vim/vimrc

- shell:
    - [vim -c 'PlugInstall' +qall, Installing vim plugins]
